# Generated by Django 4.2.1 on 2023-05-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_options_remove_cartitem_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(default=None, to='api.product'),
        ),
    ]
