# Generated by Django 4.2.1 on 2023-05-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cartitem_product_cartitem_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
