# Generated by Django 4.2.1 on 2023-05-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=''),
        ),
    ]
